### PR TITLE
updated privacy-policy & terms-of-service

### PR DESCRIPTION
**Pull request by SHADOW-LIGHTS**
### Related Issue

#190 

### Changes Made

- changed the selection color of the site
- updated privacy policy
- updated terms of service

### Screenshots
Before-
image

After-
image

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [ ] I have added necessary documentation (if applicable)

### CODE REVIEW

**Comment by Fryingpannn** [comment]
Sick tysm, could you also add changes for https://github.com/orgs/trypear/projects/7/views/1?pane=issue&itemId=73079423 as part of this PR? Just need email update!

**Comment by SHADOW-LIGHTS** [comment]
> Sick tysm, could you also add changes for https://github.com/orgs/trypear/projects/7/views/1?pane=issue&itemId=73079423 as part of this PR? Just need email update!

Yes on it

**Comment by SHADOW-LIGHTS** [comment]
Changed all emails.

**Review by Fryingpannn — APPROVED** [review]

**Comment by Fryingpannn** [comment]
Tyvm for the cleanup! Looks great

**Pull request merged**
