### PR TITLE
added dark-mode feature

### PR DESCRIPTION
**Pull request by tanishq-xin**
### Checklist

- [ ] I have tagged the issue in this PR.
- [ ] I have attached necessary screenshots.
- [ ] I have provided a short description of the PR.
- [ ] I ran `yarn build` and build is successful
- [ ] My code follows the style guidelines of this project.
- [ ] I have added necessary documentation (if applicable)

### CODE REVIEW

**Comment by Ellahinator** [comment]
Great effort on implementing the dark mode feature. However, I think we should align with shadcn's recommended approach for dark mode:

1. Use the next-themes library as outlined here: https://ui.shadcn.com/docs/dark-mode/next
2. Adjust our CSS to follow shadcn theming conventions: https://ui.shadcn.com/themes

This would simplify our implementation and make it more maintainable. It's up to you if you'd like to reimplementat this now or later - dark mode isn't a top priority at the moment, so take the time you need if you decide to refactor.

**Comment by tanishq-xin** [comment]
Switched to use `shadcn-ui` for dark mode

**Comment by Fryingpannn** [comment]
Merge conflicts 👀

**Review by ICEPrey — CHANGES_REQUESTED** [review]
## Current Approach
The current implementation is using Tailwind CSS classes with `dark:` variants to handle dark mode styling which is incorrect

```jsx
<h2 className="mb-4 text-3xl font-bold dark:text-gray-300">
  Fully{" "}
  <span className="text-primary-700 dark:text-darkPrimary-500">
    transparent
  </span>
  , PearAI is built in public
</h2>
```

This approach is adding dark mode variants directly in the JSX which is incorrect/inconvenient.

## Recommended Approach
Instead of using `dark:` variants directly in the component, it's better to leverage shadcn UI's theming system and CSS variable here is a ex:

1. Define CSS variables for the light and dark themes in our global CSS file:

```css
:root {
  --background: 0 0% 100%;
  --foreground: 222.2 84% 4.9%;
  --card: 0 0% 100%;
  --card-foreground: 222.2 84% 4.9%;
  --popover: 0 0% 100%;
  --popover-foreground: 222.2 84% 4.9%;
  --primary: 221.2 83.2% 53.3%;
  --primary-foreground: 210 40% 98%;
  --secondary: 210 40% 96.1%;
  --secondary-foreground: 222.2 47.4% 11.2%;
  --muted: 210 40% 96.1%;
  --muted-foreground: 215.4 16.3% 46.9%;
  --accent: 210 40% 96.1%;
  --accent-foreground: 222.2 47.4% 11.2%;
  --destructive: 0 84.2% 60.2%;
  --destructive-foreground: 210 40% 98%;
  --border: 214.3 31.8% 91.4%;
  --input: 214.3 31.8% 91.4%;
  --ring: 221.2 83.2% 53.3%;
  --radius: 0.5rem;
}

.dark {
  --background: 222.2 84% 4.9%;
  --foreground: 210 40% 98%;
  --card: 222.2 84% 4.9%;
  --card-foreground: 210 40% 98%;
  --popover: 222.2 84% 4.9%;
  --popover-foreground: 210 40% 98%;
  --primary: 217.2 91.2% 59.8%;
  --primary-foreground: 222.2 47.4% 11.2%;
  --secondary: 217.2 32.6% 17.5%;
  --secondary-foreground: 210 40% 98%;
  --muted: 217.2 32.6% 17.5%;
  --muted-foreground: 215 20.2% 65.1%;
  --accent: 217.2 32.6% 17.5%;
  --accent-foreground: 210 40% 98%;
  --destructive: 0 62.8% 30.6%;
  --destructive-foreground: 210 40% 98%;
  --border: 217.2 32.6% 17.5%;
  --input: 217.2 32.6% 17.5%;
  --ring: 224.3 76.3% 48%;
}
```
for specific color variants that are in tailwind config and not in the css e,g `text-primary-700` then we extend our css e.g:
 ```css
:root {
  /* Existing variables */
  --primary: 221.2 83.2% 53.3%;
  --primary-foreground: 210 40% 98%;

  /* New, more specific variables */
  --primary-50: 220 100% 98%;
  --primary-100: 221 100% 94%;
  --primary-200: 221 100% 88%;
  --primary-300: 221 100% 80%;
  --primary-400: 221 100% 70%;
  --primary-500: 221 100% 60%;
  --primary-600: 221 100% 50%;
  --primary-700: 221 100% 40%;
  --primary-800: 221 100% 30%;
  --primary-900: 221 100% 20%;

  /* Repeat for other color scales as needed */
}

.dark {
  /* Existing dark mode variables */
  --primary: 217.2 91.2% 59.8%;
  --primary-foreground: 222.2 47.4% 11.2%;

  /* New, more specific dark mode variables */
  --primary-50: 217 100% 96%;
  --primary-100: 217 100% 90%;
  --primary-200: 217 100% 80%;
  --primary-300: 217 100% 70%;
  --primary-400: 217 100% 60%;
  --primary-500: 217 100% 50%;
  --primary-600: 217 100% 40%;
  --primary-700: 217 100% 30%;
  --primary-800: 217 100% 20%;
  --primary-900: 217 100% 10%;

  /* Repeat for other color scales as needed */
}
```
this step will most likely not be needed but just in case to use these new CSS variables make sure to include it in the tailwind config e.g
```javascript
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          200: "hsl(var(--primary-200))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          900: "hsl(var(--primary-900))",
        },
        // Repeat for other color scales
      },
    },
  },
  // ... rest of your Tailwind config
};
```

Then we can jut refactor our components to use these theme colors instead of hardcoded color classes which means using only `text-primary` for both light and dark instead of creating another `dark:text-primary` variant:

```jsx
<h2 className="mb-4 text-3xl font-bold text-foreground">
  Fully{" "}
  <span className="text-primary">
    transparent
  </span>
  , PearAI is built in public
</h2>
```
if this review was a little hard to understand feel free to tell me to elaborate/assist

**Pull request closed without merging**
