### PR TITLE
Navbar redesign

### PR DESCRIPTION
**Pull request by ICEPrey**
### Description
Navbar fully refactored

### Related Issue
https://github.com/trypear/pear-landing-page/issues/213

### Changes Made
refactored everything

### Screenshots

current design:
image
image

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [x] I have added necessary documentation (if applicable)

### CODE REVIEW

**Comment by ICEPrey** [comment]
very early wip everything pretty much still needs work any help would be nice

**Comment by MitchTM17** [comment]
sorry if this isn't suuper related, but what do we think ab adding the company name next to the logo, something sorta like this:   
image_2024-08-24_194427641
and maybe making it adaptive so on smaller windows/devices it stays as just the pear logo?

**Comment by Ellahinator** [comment]
- Added `PearAI` text next to updated green logo.
- `Try PearAI` button in mobile menu now closes on click
image

**Comment by seanlodhammar** [comment]
From discord, I'll help

**Review by Fryingpannn — APPROVED** [review]

**Review by Fryingpannn — APPROVED** [review]

**Pull request merged**
