### PR TITLE
Add issue and pull request templates

### PR DESCRIPTION
**Pull request by Ibinola**
add issue and pull request templates

### CODE REVIEW

**Comment by shrix1** [comment]
Issue : https://github.com/trypear/pear-landing-page/issues/18

**Review by shrix1 — COMMENTED** [review]
@Fryingpannn Correct me if im wrong

Screenshot 2024-06-25 at 1 31 22 PM

- remove those following (check image)

- Instead of  **Your code builds clean without any errors or warnings.** can you change it to **I ran `yarn build` and build is successful**

- Add - [ ] I have added necessary documentation (if applicable)

- We dont need any of this as well 

Screenshot 2024-06-25 at 1 40 17 PM


- Other than that everything looks good, thanks @Ibinola

**Comment by Ibinola** [comment]
@shrix1 done, please review

**Comment by shrix1** [comment]
> @shrix1 done, please review

Nice. 

LGTM @Fryingpannn

**Review by Fryingpannn — APPROVED** [review]
Tysm!

**Pull request merged**
