### PR TITLE
chore: changelog v0.0.3

### PR DESCRIPTION
**Pull request by ICEPrey**
### Description
Every release I will be making a draft pr for everyone to get a little contribution if they need it (possibly resume etc) if there is no contributions then obviously I will take care of everything, and in case I miss something

### Related Issue

https://github.com/trypear/pearai-app/issues/243
### Screenshots

image

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [x] I have added necessary documentation (if applicable)

### CODE REVIEW

**Comment by Himanshu-Singh-Chauhan** [comment]
if we can keep the default dark theme of pearapp in screenshots, it would look better and consistent.

**Comment by Himanshu-Singh-Chauhan** [comment]
i think we can write some big updates in list also, like
- added mistral AI support
- easy model switching  
- Huge refactor, performance improvements
- lots of bug fixes.

please confirm with this nang and if he has more to add.

**Comment by ICEPrey** [comment]
> i think we can write some big updates in list also, like
> 
>     * added mistral AI support
> 
>     * easy model switching
>       and then what you added -
> 
>     * Huge refactor, performance improvements
> 
>     * lots of bug fixes.
> 
> 
> please confirm with this nang and if he has more to add.

yea that's why I made this a draft pr just for people to comment/add on the new updates so its easier to maintain the changelog

**Comment by ICEPrey** [comment]
> if we can keep the default dark theme of pearapp in screenshots, it would look better and consistent.

was thinking of that too needa find the theme again lol

**Comment by ICEPrey** [comment]
Commit: [897edee](https://github.com/trypear/pear-landing-page/pull/204/commits/897edeed59ff3d173392582bd6c4e351a6dc60f2) Replaced all screenshots so they all have matching themes (palm synthwave)
image

**Comment by ICEPrey** [comment]
needs changing date then can merge

**Comment by Himanshu-Singh-Chauhan** [comment]
now we need change log for 1.0.0 too 😂

**Review by Fryingpannn — APPROVED** [review]

**Pull request merged**
