### PR TITLE
prebuild prettier before yarn build

### PR DESCRIPTION
**Pull request by SHADOW-LIGHTS**
build

- Fixes issue #97 
- No errors when yarn build is run
- @Fryingpannn

### CODE REVIEW

**Review by ICEPrey — COMMENTED** [review]
The yarn format command in the prebuild script is redundant because the format script is already defined (yarn format) and can be run independently. Adding it to the prebuild step is not needed.

**Comment by SHADOW-LIGHTS** [comment]
> The yarn format command in the prebuild script is redundant because the format script is already defined (yarn format) and can be run independently. Adding it to the prebuild step is not needed.

before when yarn build was run it used to show `"[error Delete ␍eslintprettier/prettier]"` this error, now before the build process runs `prettier --write .` is run which clears all the errors and then the build process continues. 

if this is not the expected changes, can you tell me more about what exactly is it that the issue is about

**Comment by ICEPrey** [comment]
> > The yarn format command in the prebuild script is redundant because the format script is already defined (yarn format) and can be run independently. Adding it to the prebuild step is not needed.
> 
> before when yarn build was run it used to show `"[error Delete ␍eslintprettier/prettier]"` this error, now before the build process runs `prettier --write .` is run which clears all the errors and then the build process continues.
> 
> if this is not the expected changes, can you tell me more about what exactly is the issue is about

I understand that running prettier --write . before the build process helps in clearing the formatting errors that were causing issues during the build. But whats the point of running `yarn prebuild` when they can just run `yarn format` since it does the same exact thing

**Comment by ICEPrey** [comment]
> > The yarn format command in the prebuild script is redundant because the format script is already defined (yarn format) and can be run independently. Adding it to the prebuild step is not needed.
> 
> before when yarn build was run it used to show `"[error Delete ␍eslintprettier/prettier]"` this error, now before the build process runs `prettier --write .` is run which clears all the errors and then the build process continues.
> 
> if this is not the expected changes, can you tell me more about what exactly is the issue is about

also I believe this issue https://github.com/trypear/pear-landing-page/issues/97 is more related to this pr https://github.com/trypear/pear-landing-page/pull/89 since this pr actually formats the code automatically than manually formatting everytime before commit

**Pull request closed without merging**
