### PR TITLE
Revamp landing page with animations as specified

### PR DESCRIPTION
**Pull request by Rihanmulani12**
### Changes Made

Add animations to all UI elements as specified in issue

### Screenshots

Add animated background based on referenced video

https://github.com/user-attachments/assets/8141c156-1d12-41a4-9017-45278625eea9

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [x] I have added necessary documentation (if applicable)

### CODE REVIEW

**Comment by Rihanmulani12** [comment]
@nang-dev  any feedback on this ?

**Comment by Fryingpannn** [comment]
Yoo @Rihanmulani12 This looks cool. I think may be a bit too much. E.g. the animation on the cards is not necessary. I like the green on the grid lines though. 

we have finished the landing page redesign, so unfortunately you have a lot of conflicts now.

**Comment by Rihanmulani12** [comment]
can i work on this as you told?  @Fryingpannn

**Comment by Fryingpannn** [comment]
@Rihanmulani12 yes. but let's start this small. also do you make designs anywhere? would be better if we can approve designs beforehand. also what's your discord tag?

**Comment by Fryingpannn** [comment]
@Rihanmulani12 hmm u should also not be commiting .yarn. and i feel like too many installations. we should not slow website down. change should be as minimal as possible.

**Comment by Rihanmulani12** [comment]
discord tag : rihan8268 
If you provide me with any images or references for the exact design you're looking for, I can create the design in Figma myself based on your expectations. I'll also ensure it's implemented with performance optimization, so there won't be any issues with slowing down the website.

**Pull request closed without merging**
