### PR TITLE
fix footer ui

### PR DESCRIPTION
**Pull request by zeul22**
Details:
1. Centered Icon and text
2. Centered links

Before:
image

After:
image

### CODE REVIEW

**Comment by nang-dev** [comment]
probably dont wanna change yarn.lock?

**Review by Fryingpannn — COMMENTED** [review]
pls remove yarn.lock then we can merge!

**Comment by shrix1** [comment]
Should i pull this branch and remove the `yarn.lock` file

**Review by zeul22 — COMMENTED** [review]
Done. Looking forward to contributing more!

**Review by shrix1 — CHANGES_REQUESTED** [review]
Screenshot 2024-06-03 at 8 11 13 AM


@zeul22  `text-center` on the paragraph could be nice in mobile view

**Review by Fryingpannn — CHANGES_REQUESTED** [review]
Oh sht, I meant remove the change you had made in yarn.lock, not remove the file completely. So we should have this PR to only be the change in the `footer.tsx`!

**Comment by zeul22** [comment]
lol,I will make the changes with the updated yarn lock file presented on the main branch.

**Comment by zeul22** [comment]
@Fryingpannn I have added the yarn.lock as per the main branch. Let me know your thoughts

**Review by Fryingpannn — DISMISSED** [review]

**Comment by Fryingpannn** [comment]
seems like there's some conflicts due to changes I pushed for privacy policy. I think the privacy policy and ToS links should be below the social media icons actually. Would be great if u could make that change in order to resolve the conflict.

**Pull request closed without merging**
