### PR TITLE
signin/signup/reset-password pages now consistent with color scheme

### PR DESCRIPTION
**Pull request by dscreet**
image

image

image

### CODE REVIEW

**Comment by dscreet** [comment]
Should the headers be same specs as ones used on index page?

**Comment by Ellahinator** [comment]
Nice work, maybe the label text could be darker?
image

**Comment by Ellahinator** [comment]
Need to make the header texts larger on mobile display

image

image

image

**Comment by akash3444** [comment]
To ensure consistency across our website, we should consider making the input fields slightly rounded to match the design of our buttons and other components.

**Pull request merged**
